// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

const (
	Errors_MissingName    = "User_MissingName"
	Errors_ContentMissing = "User_ContentMissing"
)

func IsMissingName(err error) bool {
	return errors.Reason(err) == Errors_MissingName
}

func IsContentMissing(err error) bool {
	return errors.Reason(err) == Errors_ContentMissing
}

const (
	Errors_MissingAuth = "Auth_MissingAuth"
)

func IsMissingAuth(err error) bool {
	return errors.Reason(err) == Errors_MissingAuth
}

const (
	Errors_MissingProfile = "Profile_MissingProfile"
)

func IsMissingProfile(err error) bool {
	return errors.Reason(err) == Errors_MissingProfile
}

const (
	Errors_MissingAddress = "Address_MissingAddress"
)

func IsMissingAddress(err error) bool {
	return errors.Reason(err) == Errors_MissingAddress
}
